### ISSUE TITLE
uniswap-v3-liquidity-math.pdf Example 3

### ISSUE THREAD

**Issue by gamsterx** [atiselsts/atiselsts.github.io#1]
Hi @atiselsts, 👋 

I just went through your pdf on uniswap liquidity math and noticed a minor discrepancy on example 3 in chapter `3.2.3`. 

You wrote `Using 64-bit floating point math, the values are Lx = 219.08820141977066 and Ly = 219.08847528053587 respectively...`

I took a look at your python script and did my own calculation. On both I get `Lx = 487,417180302041` and `Ly = 487,417180030946`.

Am I missing something, or is this indeed a minor typo?

**Comment by atiselsts** [comment]
You are right - the 487.41 value must be the right one. I have updated the paper.

**Comment by gamsterx** [comment]
Thank you for your work on that paper! Helped me a lot!
